### ISSUE TITLE
能否考虑对角落里无意义的冲四进行优化处理？

### ISSUE THREAD

**Issue by Silver-Fang** [dhbloo/rapfi#14]
h2h5h4f6i6f5i5i4j6k7g6h6j5f4f3h8i2g2g3f2j4j3k5k2l1h7h9l6e3h3g7g5j8j7f8g10e9f9e10e11e8d8e7e6d7d5e5c11g9h10c4c5i10j11d9f7c10f11b11a12c7c9

无禁手，这一局Rapfi执黑败，我前后分析的感觉就是Rapfi一直绕在边边角角无意义的冲四里面来回算，导致有效的计算深度受到严重限制，因为在每个分支上都要把所有角落里的冲四以所有可能的顺序组合过一遍，这样指数爆炸下来其实浪费了很多算力……

**Comment by dhbloo** [comment]
Hi，对局面进行初步分析后，我认为主要原因在于目前的nnue对此类局面的评估有一定的偏差，导致没能在早期看出已经走入了劣势。这个问题需要等评估进一步提升后才能逐渐缓解。

另一方面，考虑到冲四在各类局面的作用不同，难以直接对冲四进行比较暴力的屏蔽处理，所以目前只能通过修改搜索的延伸和剪枝来优化。后续可能会尝试加入一些该方面的更新。
