### ISSUE TITLE
When will ARMv8 build option be introduced for Android?

### ISSUE THREAD

**Issue by wuwbobo2021** [dhbloo/rapfi#15]
According to this article (https://simd-everywhere.github.io/blog/2020/06/22/transitioning-to-arm-with-simde.html), it isn't too difficult to migrate the program to ARM NEON. I think you've already condidered this but have faced some difficulties, would you like to explain here?

I've found some related code files: `core/platform.h`, `eval/simdops.h`, `CMakeLists.txt`, `CMakeSettings.json`. At this moment, I can't do these things for myself as an amateur.

另外，取个中文名字怎么样？

**Comment by dhbloo** [comment]
Hi, ARM build is in the roadmap, and I will see if I can add it in the later 1 or 2 weeks. Currently, SIMDE is used in the older NNUE part, but I am already planning to remove the dependency on it, as I found that the implicit performance loss might be a lot. To achieve maximum efficiency, it might be necessary to manually overload for different architectures.

Thanks for your advice on the logo. I have not come up with a good Chinese name yet, thus by this time most people use its transliteration "拉菲"。

**Comment by Liberations** [comment]
> Hi, ARM build is in the roadmap, and I will see if I can add it in the later 1 or 2 weeks. Currently, SIMDE is used in the older NNUE part, but I am already planning to remove the dependency on it, as I found that the implicit performance loss might be a lot. To achieve maximum efficiency, it might be necessary to manually overload for different architectures.
> 
> Thanks for your advice on the logo. I have not come up with a good Chinese name yet, thus by this time most people use its transliteration "拉菲"。

为你的付出点赞。如何编译到android上运行？有方案了吗

**Comment by dhbloo** [comment]
Full support for arm64/armv8a has now been merged into master. If you would like to compile with ARM NEON (arch=armv8-a+simd), you can specify `USE_NEON=ON` for cmake config (and remember to set `USE_SSE=OFF` and `USE_AVX2=OFF`). 

Additionally, you can optionally enable ARM NEON with int8 DOTPROD support (arch=armv8.2-a+dotprod) with `USE_NEON_DOTPROD=ON`.
