### ISSUE TITLE
算出杀以后能否继续后台思考？

### ISSUE THREAD

**Issue by Silver-Fang** [dhbloo/rapfi#17]
现在好像算出杀以后后台就不再思考了，特别是有数据库的时候。但有时候当前的线路可能不是最优解，还可以再优化减少步数，所以是否应该继续后台思考，尝试寻找更少步数的杀？

**Comment by Silver-Fang** [comment]
这个问题在防守的时候也很严重。只要算出了必杀，后续就不再思考了，往往会走一步弱防，导致原本很多步才能杀的局面变成简单杀了。

**Comment by dhbloo** [comment]
了解。后台思考目前的逻辑是算到必胜/必败之后再搜索N层，其中N可以用config.toml中的num_iteration_after_mate设置。
你可以尝试将该值设置为一个较大的数字。
