### ISSUE TITLE
Is OpenCL accelerator possible?

### ISSUE THREAD

**Issue by wuwbobo2021** [dhbloo/rapfi#20]
Inspired by a simple program published by @nguyencongminh090, I tried another way of score counting. The code is here: <https://github.com/nguyencongminh090/CaroAI_BACKEND/issues/1>.

Lacking real interest in the game, I’ve decided not to make more efforts in this direction. Please close or delete this issue when you read it.

PS: nguyencongminh090 have said that he needs some help. Only enthusiasts like you can help him.

**Comment by dhbloo** [comment]
Is it a method to compute classical evaluation? The code is not short, so I may need some time to read it.

**Comment by wuwbobo2021** [comment]
Sorry, I don’t understand what is “classic”. It’s merely counting statically for groups of stones that may extend to length 5 in the future. You can check the function marked as `#[test]` If the entire program is too long. Thanks.

**Comment by wuwbobo2021** [comment]
这个设想是有严重缺点还是毫无意义? 请指教。
