### ISSUE TITLE
[疑问] Win引擎只需要一个exe？其它文件重要吗？

### ISSUE THREAD

**Issue by ghost** [dhbloo/rapfi#21]
我在Win系统运行piskvork界面，只需要一个pbrain-rapfi_windows_avx2.exe？？
model210901.bin 和 mix9freestyle_*.bin.lz4 有什么用的？需要放一起才能发挥最强算力的吗？
谢谢帮忙！

**Comment by dhbloo** [comment]
Hi,

`pbrain-rapfi.exe`是引擎程序，`model210901.bin`和`mix9freestyle_*.bin.lz4`分别是传统估值和nnue估值的权重文件，所有文件和`config.toml`文件放在同一个目录下，引擎就可以正常运行。
