### ISSUE TITLE
pbrain-rapfi_windows_avx2.exe: Transposition table: Windows Large-Page memory is used.

### ISSUE THREAD

**Issue by AcademicDog** [dhbloo/rapfi#22]
1) pbrain-rapfi_windows_avx2.exe: Transposition table: Windows Large-Page memory is used.
 1) pbrain-rapfi_windows_avx2.exe: Load config from "D:\\Programs\\piskvork\\RAFI\\config.toml"
 1) pbrain-rapfi_windows_avx2.exe: Transposition table: Windows Large-Page memory is used.
 1) pbrain-rapfi_windows_avx2.exe: Evaluator set to mix9nnue.
 0) pbrain-rapfi_windows_avx2.exe: Transposition table: Windows Large-Page memory is used.
 0) pbrain-rapfi_windows_avx2.exe: Load config from "D:\\Programs\\piskvork\\RAFI\\config.toml"
 0) pbrain-rapfi_windows_avx2.exe: Transposition table: Windows Large-Page memory is used.
 0) pbrain-rapfi_windows_avx2.exe: Evaluator set to mix9nnue.

**Comment by dhbloo** [comment]
这个是正常现象，该输出表示使用了Windows的Large Page memory机制，在内存访问速度上有一定的提升。
