### ISSUE TITLE
Missing Worker File in Multi-Threaded WASM Build

### ISSUE THREAD

**Issue by vkuprin** [dhbloo/rapfi#23]
I am trying to build a multi-threaded WebAssembly version of Rapfi using a custom Makefile, but the .worker.js file required for threading is not being generated.

Here is my setup:
	•	Emscripten version: [3.1.74]
	•	Custom Makefile:

```Makefile
BUILD_DIR_MULTI := build-multi
OUTPUT_DIR := wasm-output
COMMON_FLAGS := -DCMAKE_BUILD_TYPE=Release \
                -DNO_COMMAND_MODULES=ON \
                -DUSE_SSE=OFF \
                -DUSE_AVX2=OFF \
                -DUSE_AVX512=OFF \
                -DUSE_BMI2=OFF \
                -DUSE_VNNI=OFF

EMSCRIPTEN_FLAGS := -s USE_PTHREADS=1 \
                    -s PTHREAD_POOL_SIZE=4 \
                    -s MODULARIZE=1 \
                    -s EXPORT_NAME="createRapfiModule" \
                    -s PROXY_TO_PTHREAD=1

multi:
	mkdir -p $(BUILD_DIR_MULTI)
	cd $(BUILD_DIR_MULTI) && emcmake cmake .. $(COMMON_FLAGS) -DNO_MULTI_THREADING=OFF
	cd $(BUILD_DIR_MULTI) && emmake make CXXFLAGS="$(EMSCRIPTEN_FLAGS)" LDFLAGS="$(EMSCRIPTEN_FLAGS)"
	mkdir -p $(OUTPUT_DIR)
	cp $(BUILD_DIR_MULTI)/*.wasm $(BUILD_DIR_MULTI)/*.js $(BUILD_DIR_MULTI)/*.data $(OUTPUT_DIR)/
	@if [ -e $(BUILD_DIR_MULTI)/*.worker.js ]; then \
	  cp $(BUILD_DIR_MULTI)/*.worker.js $(OUTPUT_DIR)/; \
	else \
	  echo "Warning: No worker file found. Ensure PROXY_TO_PTHREAD is properly set in your configuration."; \
	fi
```

Despite including the necessary Emscripten flags (USE_PTHREADS, PROXY_TO_PTHREAD, etc.), the .worker.js file is not generated in the build directory

The gomoku-calculator repository has precompiled multi-threaded WASM files, including a worker file, in its public/build directory ([link to relevant folder](https://github.com/dhbloo/gomoku-calculator/tree/87edc92a07ef3007fe57116d8c4d83cf20e7b2c7/public/build)). How were those files built, and what configurations or flags are required to replicate this?

Could you please confirm if there are any additional steps or configurations required to generate the worker file for multi-threaded builds in Rapfi?

**Comment by dhbloo** [comment]
Hi,

According to emscripten's [changelog](https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3168---093024) and [commit history](https://github.com/sbc100/emscripten/commit/9c3f2afa4dbeadf37c9211ff6fe322482d0ac5ec), it no longer produces a separate worker.js file and the content of worker is bundled into the main output. So the output you get should be okay.

For detailed compilation configurations, you can refer to [this section](https://github.com/dhbloo/rapfi/blob/58ed3f3cd1cf00c3ac3f002f61425625e9d91fa9/Rapfi/CMakeLists.txt#L179-L255) of the CMakeList. There are some parts that are crucial to get rapfi running properly and efficiently in WASM:
+ Emscripten bundles the runtime files when building, so you need to preload the config and network files like [this](https://github.com/dhbloo/rapfi/blob/58ed3f3cd1cf00c3ac3f002f61425625e9d91fa9/Rapfi/CMakeLists.txt#L210-L216), where the `Networks/wasm_preloads.txt` records all the files you need to tell emscripten to preload. I have upgraded the WASM code to support the latest mix9nnuelite which should be much stronger than the old gomocalc version.
+ Some glue code is need to communicate with rapfi in the JS code. It is implemented in premable.js and you only need to add this [line](https://github.com/dhbloo/rapfi/blob/58ed3f3cd1cf00c3ac3f002f61425625e9d91fa9/Rapfi/CMakeLists.txt#L198) to the emscripten arguments. You can test the build output with [this HTML code](https://gist.github.com/dhbloo/2e08e65392713dd88d4e321fc63aff89).
+ For better computation speed, it's recommended to enable `USE_WASM_SIMD` option (and more advanced `USE_WASM_SIMD_RELAXED`). However, [WebAssembly SIMD feature](https://caniuse.com/wasm-simd) is not fully supported on all browsers, just like the [SharedArrayBuffer](https://caniuse.com/sharedarraybuffer) for multi-threading. For best compatibility, it's recommended to build a matrix of different configurations (rapfi-single | rapfi-multi | rapfi-single-simd128 | rapfi-multi-128), and load the correct version according to the [capability detected](https://github.com/GoogleChromeLabs/wasm-feature-detect) in the JS code.

**Comment by vkuprin** [comment]
Thank you for such an informative explanation ✅
